### ISSUE TITLE
The intervene venn diagram is misleading

### ISSUE THREAD

**Issue by danli349** [asntech/intervene#53]
I found that The `intervene venn` diagram is misleading.
I use the peak `summits` file and `narrowPeak` file of the same sample to do `intervene venn`,
All  of the summits are in narrowPeaks:

```
intervene venn -i macs2_2/DoxCD31mKATEpos3_summits.bed \
macs2_2/DoxCD31mKATEpos3_peaks.narrowPeak \
--names summits,narrowPeak \
--bedtools-options f=1bp \
--title DoxCD31mKATEpos3 \
-o venn \
--figsize 12 12 \
--fontsize 14 \
--dpi 300 \
--project DoxCD31mKATEpos3
```

When A overlap with B:
The left area label (no overlap area) is total of A subtract overlap
The right area label (no overlap area) is total of B.

It is better to show right area label with total of B subtract overlap.

![image](https://user-images.githubusercontent.com/33963919/193279514-1f7eba19-4db8-4bbc-9d72-206e8c5d45d0.png)

**Comment by asntech** [comment]
@danli349 this is because you're setting the -f and not -F, and also, you don't need to set `--bedtools-options f=1bp` since bedtools by default works as 1bp, not as a fraction of A or B. The description of the fraction of A/B args of `bedtools intersect` are below. For try without `--bedtools-options f=1bp` - it should work. 

-f | Minimum overlap required as a fraction of A. Default is 1E-9 (i.e. 1bp).
-- | --
-F | Minimum overlap required as a fraction of B. Default is 1E-9 (i.e., 1bp).

**Comment by danli349** [comment]
Yes. I tried without `--bedtools-options f=1bp` it works perfect.
Thanks a lot.

**Comment by asntech** [comment]
Great!
