### ISSUE TITLE
How can I turn the type 3 font off in the out.pdf？

### ISSUE THREAD

**Issue by yangluom** [asntech/intervene#7]
Hey man, when I draw venn diagram based on bed files, intervene works well, but when I tried to modify the font of the texts in the out.pdf, it shows "Edit Text Tool doesn't support the type 3 font".how can i deal with it? Or how can I turn the font of  out.pdf from type 3 font to type 1 font?
And, one more question, how can make the outputs of intervene with both out.pdf and Rscripts?
Many thanks!

**Comment by asntech** [comment]
Hi @yangluom please try the latest version v0.6.4. For Venn diagrams I am using matplotlib which by default uses Type-3 fount now I've customized it to the True-Type font. https://matplotlib.org/users/customizing.html

For question 2, since we are using Python for Venn plots you can not get the Rscript. I will consider to add this feature in the future releases. Thanks and sorry for late response.

Aziz

**Comment by asntech** [comment]
You're welcome!
